import Slate from "./roofing/GAF Timberline HD SLATE-model.jpg";

export const slservices = [
  {
    id: 1,
    title: "Metal Roofing",
    img: "Metal Roofing",
    category: ["Roofing"],
  },
  {
    id: 2,
    title: "Clay (Spanish) Tile Roofing",
    img: "Tile Roofing",
    category: ["Roofing"],
  },
  {
    id: 3,
    title: "Slate Roofing",
    img: Slate,
    category: ["Roofing"],
  },
  {
    id: 4,
    title: "EPDM - TPO Rubber Roofing",
    img: "Rubber Roofing",
    category: ["Roofing"],
  },
  {
    id: 5,
    title: "Architectural Composition/Asphalt Shingles",
    img: "Asphalt Shingles",
    category: ["Roofing"],
  },
  {
    id: 6,
    title: "Wood Shingles - Wood Shake",
    img: "Wood Shingles",
    category: ["Roofing"],
  },
  {
    id: 7,
    title: "Vinly Siding",
    img: "Vinly Siding",
    category: ["Siding"],
  },
  {
    id: 8,
    title: "Wood Siding",
    img: "Wood Siding",
    category: ["Siding"],
  },
  {
    id: 9,
    title: "Metal Siding",
    img: "Metal Siding",
    category: ["Siding"],
  },
  {
    id: 10,
    title: "Stucco Siding",
    img: "Stucco Siding",
    category: ["Siding"],
  },
  {
    id: 11,
    title: "Stone Siding",
    img: "Stone Siding",
    category: ["Siding"],
  },
  {
    id: 12,
    title: "Brick Siding",
    img: "Brick Siding",
    category: ["Siding"],
  },
  {
    id: 13,
    title: "Engineered Wood - LP Smart Siding",
    img: "LP Smart Siding",
    category: ["Siding"],
  },
  {
    id: 14,
    title: "Aluminum Gutters",
    img: "Aluminum Gutters",
    category: ["Gutters"],
  },
  {
    id: 15,
    title: "Copper Gutters",
    img: "Copper Gutters",
    category: ["Gutters"],
  },
  {
    id: 16,
    title: "Zinc Gutters",
    img: "Zinc Gutters",
    category: ["Gutters"],
  },
  {
    id: 17,
    title: "Steel Gutters",
    img: "Steel Gutters",
    category: ["Gutters"],
  },
  {
    id: 18,
    title: "K Style and Half Round Gutters",
    img: "K Style and Half Round Gutters",
    category: ["Gutters"],
  },
  {
    id: 19,
    title: "Casement Windows",
    img: "Casement Windows",
    category: ["Others"],
  },
  {
    id: 20,
    title: "Slider Windows",
    img: "Slider Windows",
    category: ["Others"],
  },
  {
    id: 21,
    title: "Double Hung Windows",
    img: "Double Hung Windows",
    category: ["Others"],
  },
  {
    id: 22,
    title: "Awning Windows",
    img: "Awning Windows",
    category: ["Others"],
  },
  {
    id: 23,
    title: "Skylight Windows",
    img: "Skylight Windows",
    category: ["Others"],
  },
  {
    id: 24,
    title: "Egress Windows",
    img: "Egress Windows",
    category: ["Others"],
  },
  {
    id: 25,
    title: "Picture Windows",
    img: "Picture Windows",
    category: ["Others"],
  },
  {
    id: 26,
    title: "Garden Windows",
    img: "Garden Windows",
    category: ["Others"],
  },
  {
    id: 27,
    title: "Bow Windows",
    img: "Bow Windows",
    category: ["Others"],
  },
  {
    id: 28,
    title: "Bay Windows",
    img: "Bay Windows",
    category: ["Others"],
  },
  {
    id: 29,
    title: "Sliding Doors",
    img: "Sliding Doors",
    category: ["Others"],
  },
  {
    id: 30,
    title: "French Doors",
    img: "French Doors",
    category: ["Others"],
  },
  {
    id: 31,
    title: "Bi-fold Doors",
    img: "Bi-fold Doors",
    category: ["Others"],
  },
  {
    id: 32,
    title: "Pocket Doors",
    img: "Pocket Doors",
    category: ["Others"],
  },
  {
    id: 33,
    title: "Hinged Doors",
    img: "Hinged Doors",
    category: ["Others"],
  },
  {
    id: 34,
    title: "Battened and Ledged Doors",
    img: "Battened and Ledged Doors",
    category: ["Others"],
  },
  {
    id: 34,
    title: "Dutch Doors",
    img: "Dutch Doors",
    category: ["Others"],
  },
  {
    id: 35,
    title: "Roller Doors",
    img: "Roller Doors",
    category: ["Others"],
  },
];
